# Generated by Django 2.1.5 on 2019-04-03 18:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ajax_crud', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='User',
            new_name='Visitor',
        ),
    ]
