# Generated by Django 2.1.5 on 2019-03-22 13:33

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('sid', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('grad_date', models.DateTimeField()),
                ('score', models.IntegerField(max_length=3)),
            ],
        ),
    ]
